# -*- coding: utf-8 -*-
"""AI fin chat.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14j576KSfBAhxTQwqEItNcG6UxFjlxXks

1: Install Packages
"""

!pip install streamlit yfinance pandas plotly google-generativeai

"""Cell 2: Create app.py"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# import pandas as pd
# import yfinance as yf
# import plotly.express as px
# import google.generativeai as genai
# 
# # Configure Gemini
# API_KEY = st.secrets["GOOGLE_API_KEY"]
# 
# genai.configure(api_key=API_KEY)
# 
# model = genai.GenerativeModel("gemini-3-flash")
# 
# st.set_page_config(
#     page_title="AI Financial Advisor",
#     layout="wide"
# )
# 
# st.title("AI Financial Advisory Chatbot")
# 
# income = st.sidebar.number_input(
#     "Monthly Income",
#     min_value=0
# )
# 
# expenses = st.sidebar.number_input(
#     "Monthly Expenses",
#     min_value=0
# )
# 
# goal = st.sidebar.number_input(
#     "Savings Goal",
#     min_value=0
# )
# 
# symbol = st.sidebar.text_input(
#     "Enter NSE Symbol",
#     value="INFY.NS"
# )
# 
# question = st.text_area(
#     "Ask Financial Question"
# )
# 
# if st.button("Analyze"):
# 
#     stock = yf.Ticker(symbol)
# 
#     info = stock.info
# 
#     history = stock.history(period="1mo")
# 
#     st.subheader("Company Information")
# 
#     st.write(
#         {
#             "Company": info.get("longName"),
#             "Sector": info.get("sector"),
#             "Current Price": info.get("currentPrice")
#         }
#     )
# 
#     fig = px.line(
#         history,
#         y="Close",
#         title="Price Trend"
#     )
# 
#     st.plotly_chart(fig)
# 
#     prompt = f"""
#     Monthly Income = {income}
# 
#     Monthly Expenses = {expenses}
# 
#     Savings Goal = {goal}
# 
#     Company = {info.get('longName')}
# 
#     Current Price = {info.get('currentPrice')}
# 
#     User Question:
#     {question}
# 
#     Give:
#     1. Budget Analysis
#     2. Savings Advice
#     3. Investment Suggestions
#     4. Risk Assessment
#     """
# 
#     response = model.generate_content(prompt)
# 
#     st.subheader("AI Recommendation")
# 
#     st.write(response.text)

"""3: Create requirements.txt"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile requirements.txt
# streamlit
# yfinance
# pandas
# plotly
# google-generativeai

"""4: Download Files"""

from google.colab import files

files.download("app.py")
files.download("requirements.txt")

"""Streamlit Secret"""

GOOGLE_API_KEY="AQ.Ab8RN6LrBohIKbQw2LeT631IHK_MnGqjJUrFvduhfg7af4i5KQ"